version: '3'

services:
  mysql:
    image: mysql
    restart: always
    ports:
      - '3307:3306'
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
      MYSQL_ROOT_PASSWORD: Qwerty123
      MYSQL_DATABASE: users_db
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  adminer:
    image: adminer
    restart: always
    ports:
      - '8888:8080'
    volumes:
    - mysql_data:/designs
 
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: Qwerty123
    ports:
      - "8889:80"
    depends_on:
      - mysql



volumes:
  mysql_data: